name: Tauron Reader
version: "3.9.2"
slug: tauron_reader
description: Addon to fetch energy data from Tauron eLicznik and insert into MySQL database
url: "https://github.com/ussdeveloper/home-assistant-addons"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:flash
panel_title: "Tauron Reader"
options:
  database:
    host: "localhost"
    port: 3306
    user: "user"
    password: "password"
    name: "database"
    table: "energy_extend"
  tauron:
    username: "your_tauron_username"
    password: "your_tauron_password"
  schedule:
    times: ["02:00", "10:00"]
  http:
    port: 8765
schema:
  database:
    host: str
    port: int
    user: str
    password: password
    name: str
    table: str
  tauron:
    username: str
    password: password
  schedule:
    times:
      - str
  http:
    port: int
ports:
  8765/tcp: 8765
ports_description:
  8765/tcp: "Web interface for Tauron Reader"